//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Collections.Generic;
    
    public partial class details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public details()
        {
            this.produkty = new HashSet<produkty>();
        }
    
        public decimal ID_DETAILS { get; set; }
        public Nullable<decimal> ILOSC_GLOSNIKOW { get; set; }
        public string MATRYCA { get; set; }
        public Nullable<decimal> POJEMNOSC { get; set; }
        public Nullable<decimal> ILOSC_POLEK { get; set; }
        public string RODZAJ_RADIA { get; set; }
        public string OPIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produkty> produkty { get; set; }
    }
}
