//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class retro_sklepEntities : DbContext
    {
        public retro_sklepEntities()
            : base("name=retro_sklepEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<details> details { get; set; }
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<poz_transakcje> poz_transakcje { get; set; }
        public virtual DbSet<producenci> producenci { get; set; }
        public virtual DbSet<produkty> produkty { get; set; }
        public virtual DbSet<transakcje> transakcje { get; set; }
        public virtual DbSet<dzialajacyProducenci> dzialajacyProducenci { get; set; }
        public virtual DbSet<kupionePrzedmioty> kupionePrzedmioty { get; set; }
        public virtual DbSet<produktyDoRenowacji> produktyDoRenowacji { get; set; }
    }
}
