//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Collections.Generic;
    
    public partial class poz_transakcje
    {
        public decimal ID_WIERSZA { get; set; }
        public Nullable<decimal> ID_TRANSAKCJI { get; set; }
        public Nullable<decimal> ID_PRODUKTU { get; set; }
    
        public virtual produkty produkty { get; set; }
        public virtual transakcje transakcje { get; set; }
    }
}
