//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Collections.Generic;
    
    public partial class produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produkty()
        {
            this.poz_transakcje = new HashSet<poz_transakcje>();
        }
    
        public decimal ID_PRODUKTU { get; set; }
        public decimal ID_DETAILS { get; set; }
        public string NAZWA { get; set; }
        public string TWORZYWO { get; set; }
        public decimal CENA { get; set; }
        public string DO_RENOWACJI { get; set; }
        public decimal SZEROKOSC { get; set; }
        public decimal GŁĘBOKOSC { get; set; }
        public decimal WYSOKOSC { get; set; }
        public byte[] ZDJECIE { get; set; }
        public Nullable<System.DateTime> ROK_PRODUKCJI { get; set; }
        public decimal ID_PRODUCENTA { get; set; }
    
        public virtual details details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poz_transakcje> poz_transakcje { get; set; }
        public virtual producenci producenci { get; set; }
    }
}
