//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Collections.Generic;
    
    public partial class producenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producenci()
        {
            this.produkty = new HashSet<produkty>();
        }
    
        public decimal ID_PRODUCENTA { get; set; }
        public string NAZWA { get; set; }
        public System.DateTime ROK_ZALOZENIA { get; set; }
        public string CZY_AKTYWNY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produkty> produkty { get; set; }
    }
}
