//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroSprzety___v6
{
    using System;
    using System.Collections.Generic;
    
    public partial class transakcje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public transakcje()
        {
            this.poz_transakcje = new HashSet<poz_transakcje>();
        }
    
        public decimal ID_TRANSAKCJI { get; set; }
        public decimal ID_KLIENTA { get; set; }
    
        public virtual klienci klienci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<poz_transakcje> poz_transakcje { get; set; }
    }
}
